{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-tls
  namespace: default
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecrets.certificates.crt | b64enc }}
  tls.key: {{ .Values.tlsSecrets.certificates.key | b64enc }}
{{- end }}